version: '3.9'

networks:
  app:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - maindb
    networks:
      - app

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - app

  composer:
      image: composer:latest
      container_name: composer
      volumes:
        - ./src:/var/www/html
      working_dir: /var/www/html
      depends_on:
        - php
      user: root
      entrypoint: [ 'composer', '--ignore-platform-reqs' ]
      networks:
        - app

  artisan:
      build:
        context: ./dockerfiles
        dockerfile: php.dockerfile
      container_name: artisan
      volumes:
        - ./src:/var/www/html:delegated
      depends_on:
        - maindb
      working_dir: /var/www/html
      entrypoint: [ 'php', '/var/www/html/artisan' ]
      networks:
        - app

  maindb:
      image: postgres
      restart: always
      ports:
        - "5433:5433"
      environment:
        POSTGRES_DB: product_service
        POSTGRES_USER: jonecoder
        POSTGRES_PASSWORD: password
      volumes:
        - ./data/postgresql:/var/lib/postgresql/data
      networks:
        - app